### ISSUE TITLE
npm ERR! could not determine executable to run 

### ISSUE THREAD

**Issue by kernaltrap8** [NanderTGA/windows96-local-2.0#2]
this happens when i try to run `npx toc`

log file:

```
0 verbose cli C:\nodejs\node.exe C:\Users\user\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@9.2.0
2 info using node@v16.17.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:C:\Users\user\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 5ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\user\Downloads\windows96-local-2.0-main\windows96-local-2.0-main\.npmrc Completed in 1ms
10 timing config:load:project Completed in 8ms
11 timing config:load:file:C:\Users\user\.npmrc Completed in 4ms
12 timing config:load:user Completed in 5ms
13 timing config:load:file:C:\Users\user\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 31ms
17 timing npm:load:configload Completed in 31ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm exec toc
21 verbose argv "exec" "--" "toc"
22 timing npm:load:setTitle Completed in 3ms
23 timing config:load:flatten Completed in 6ms
24 timing npm:load:display Completed in 8ms
25 verbose logfile logs-max:10 dir:C:\Users\user\AppData\Local\npm-cache\_logs\2023-01-05T18_06_46_960Z-
26 verbose logfile C:\Users\user\AppData\Local\npm-cache\_logs\2023-01-05T18_06_46_960Z-debug-0.log
27 timing npm:load:logFile Completed in 14ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 59ms
31 silly logfile start cleaning logs, removing 2 files
32 timing config:load:flatten Completed in 1ms
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 2ms
35 timing arborist:ctor Completed in 0ms
36 http fetch GET 200 https://registry.npmjs.org/toc 224ms (cache revalidated)
37 timing command:exec Completed in 583ms
38 verbose stack Error: could not determine executable to run
38 verbose stack     at getBinFromManifest (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
38 verbose stack     at exec (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:187:15)
38 verbose stack     at async module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\cli.js:133:5)
39 verbose pkgid toc@0.4.0
40 verbose cwd C:\Users\user\Downloads\windows96-local-2.0-main\windows96-local-2.0-main
41 verbose Windows_NT 10.0.22000
42 verbose node v16.17.0
43 verbose npm  v9.2.0
44 error could not determine executable to run
45 verbose exit 1
46 timing npm Completed in 710ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     C:\Users\user\AppData\Local\npm-cache\_logs\2023-01-05T18_06_46_960Z-debug-0.log

```
when i run the `node "rofs downloader.js" https://windows96.net` command, i get `MODULE_NOT_FOUND`. 

**real username has been replaced with `user` for security.**

**Comment by kernaltrap8** [comment]
nevermind, i read the README wrong. ran `npx toc` instead of `npx tsc`
